# Generated by Django 3.2.4 on 2021-07-02 12:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Discussion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Discuss', models.CharField(max_length=1000)),
                ('Forum', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.forums')),
            ],
        ),
    ]
